spring:
  profiles:
    active: development
---
spring:
  profiles: development
  jpa:
    database-platform: org.hibernate.dialect.ProgressDialect
server:
  port: 8083
---
datasource:
  openedge:
    url: jdbc:datadirect:openedge://c217u083.cg.na.jci.com:50963;DatabaseName=symix;
    username: E2Open
    password: nepO2E01
    driver-class-name: com.ddtek.jdbc.openedge.OpenEdgeDriver
    validation-query: select 1
    max-active: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework: INFO
    com.jci: DEBUG  
---
spring:
  profiles: cloud
server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
